[package]
name = "wiki_bot"
version = "0.1.0"
authors = ["Hyijun <text@hyijun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.7.1"
regex = "1"
chrono="0.4.7"
rustc-serialize = "0.3.18"